default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: recipe_app_development
  username: shafiu
  password: "Soccer"

test:
  <<: *default
  database: recipe_app_test
  username: shafiu
  password: "Soccer"

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: render_deploy_production
  username: render_deploy
  password: <%= ENV["RENDER_DEPLOY_DATABASE_PASSWORD"] %>
